apiVersion: v1
kind: Service
metadata:
  name: chat-server-service
spec:
  type: NodePort
  selector:
    app: chat-server
  ports:
  - port: 4333
    targetPort: 4333
    nodePort: 31515
